.TH SONATA 1 "October 20, 2006"
.SH NAME
sonata \- GTK+ client for the Music Player Daemon
.SH SYNOPSIS
.B sonata
[\fIOPTION\fR]
.SH DESCRIPTION
Sonata is an elegant GTK+ music client for the Music Player Daemon (MPD).
.SH OPTIONS
.TP
.B \-h\fR, \fB\-\-help
Show this help and exit
.TP
.B \-p\fR, \fB\-\-popup
Popup song notification (requires D\-Bus)
.TP
.B \-t\fR, \fB\-\-toggle
Toggles whether the app is minimized to tray or visible (requires D\-Bus)
.TP
.B \-v\fR, \fB\-\-version
Show version information and exit
.TP
.B \-\-hidden
Start app hidden (requires systray)
.TP
.B \-\-visible
Start app visible (requires systray)
.TP
.B \-\-profile\=[NUM]
Start with profile [NUM]
.TP
.B play
Play song in playlist
.TP
.B pause
Pause currently playing song
.TP
.B stop
Stop currently playing song
.TP
.B next
Play next song in playlist
.TP
.B prev
Play previous song in playlist
.TP
.B pp
Toggle play/pause; plays if stopped
.TP
.B repeat
Toggle repeat mode
.TP
.B random
Toggle random mode
.TP
.B info
Display current song info
.TP
.B status
Display MPD status
.SH "SEE ALSO"
.PP
Website: http://sonata.berlios.de
.PP
MPD Website: http://www.musicpd.org
.SH AUTHOR
Sonata was written by Scott Horowitz <stonecrest@gmail.com>.

.PP
This manual page is currently maintained by Scott Horowitz 
<stonecrest@gmail.com>. It was originally written by Michal Cihar 
<michal@cihar.com>.
