#!/bin/sh

cd $(dirname "$0")
cd ..

echo
echo Updating POTFILES.in...
find setup.py sonata \( -name "*.py" -o -name "*.glade" \) > po/POTFILES.in

cd po
echo Update messages.po...
echo

intltool-update -p
mv untitled.pot messages.po

for i in *.po
do
    if [ "$i" = "messages.po" ]
    then
        continue
    fi
    echo Updating ${i}...
    intltool-update "${i%*.po}"
    echo
done

echo Cleaning up...
echo

rm untitled.pot
