#!/bin/sh

PACKAGE=Sonata
INTLTOOL_UPDATE="intltool-update --gettext-package=$PACKAGE"

if ! which intltool-update > /dev/null
then
    echo "You need intltool-update to update the translation files!" > /dev/fd/2
    exit 1
fi

cd $(dirname "$0")/../po

rm -f missing
echo Updating POTFILES.in...
$INTLTOOL_UPDATE -m

if [ -f missing ]
then
    exit 1
fi

echo Updating $PACKAGE.pot...
$INTLTOOL_UPDATE -p

for i in *.po
do
    # Generate ;po files only for the specified language.
    echo "$*" | grep -q "$(echo $i | sed "s/.po$//g")"
    if [ $? = 0 -o $# = 0 ]
    then
        echo Updating $i...
        $INTLTOOL_UPDATE "${i%*.po}"

        echo Purging old translations from $i...
        msgattrib --output-file="$i" --no-obsolete "$i"
    fi
done


echo "Translation status:"
$INTLTOOL_UPDATE -r
